/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroContaRouteImport } from './routes/cadastro-conta'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelCadastroRouteImport } from './routes/painel.cadastro'
import { Route as PainelExtratoRouteImport } from './routes/painel.extrato'
import { Route as PainelGraficosRouteImport } from './routes/painel.graficos'
import { Route as PainelPerfilRouteImport } from './routes/painel.perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroContaRoute = CadastroContaRouteImport.update({
  id: '/cadastro-conta',
  path: '/cadastro-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCadastroRoute = PainelCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => PainelRoute,
} as any)
const PainelExtratoRoute = PainelExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => PainelRoute,
} as any)
const PainelGraficosRoute = PainelGraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPerfilRoute = PainelPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro-conta': typeof CadastroContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/painel/cadastro': typeof PainelCadastroRoute
  '/painel/extrato': typeof PainelExtratoRoute
  '/painel/graficos': typeof PainelGraficosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro-conta': typeof CadastroContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/painel/cadastro': typeof PainelCadastroRoute
  '/painel/extrato': typeof PainelExtratoRoute
  '/painel/graficos': typeof PainelGraficosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro-conta': typeof CadastroContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/painel/cadastro': typeof PainelCadastroRoute
  '/painel/extrato': typeof PainelExtratoRoute
  '/painel/graficos': typeof PainelGraficosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro-conta'
    | '/esqueci-senha'
    | '/login'
    | '/painel'
    | '/reset-password'
    | '/painel/cadastro'
    | '/painel/extrato'
    | '/painel/graficos'
    | '/painel/perfil'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro-conta'
    | '/esqueci-senha'
    | '/login'
    | '/reset-password'
    | '/painel/cadastro'
    | '/painel/extrato'
    | '/painel/graficos'
    | '/painel/perfil'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/cadastro-conta'
    | '/esqueci-senha'
    | '/login'
    | '/painel'
    | '/reset-password'
    | '/painel/cadastro'
    | '/painel/extrato'
    | '/painel/graficos'
    | '/painel/perfil'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroContaRoute: typeof CadastroContaRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-conta': {
      id: '/cadastro-conta'
      path: '/cadastro-conta'
      fullPath: '/cadastro-conta'
      preLoaderRoute: typeof CadastroContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/cadastro': {
      id: '/painel/cadastro'
      path: '/cadastro'
      fullPath: '/painel/cadastro'
      preLoaderRoute: typeof PainelCadastroRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/extrato': {
      id: '/painel/extrato'
      path: '/extrato'
      fullPath: '/painel/extrato'
      preLoaderRoute: typeof PainelExtratoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/graficos': {
      id: '/painel/graficos'
      path: '/graficos'
      fullPath: '/painel/graficos'
      preLoaderRoute: typeof PainelGraficosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/perfil': {
      id: '/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof PainelPerfilRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelCadastroRoute: typeof PainelCadastroRoute
  PainelExtratoRoute: typeof PainelExtratoRoute
  PainelGraficosRoute: typeof PainelGraficosRoute
  PainelPerfilRoute: typeof PainelPerfilRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelCadastroRoute: PainelCadastroRoute,
  PainelExtratoRoute: PainelExtratoRoute,
  PainelGraficosRoute: PainelGraficosRoute,
  PainelPerfilRoute: PainelPerfilRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroContaRoute: CadastroContaRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
